server:
  port: 8082

spring:
  data:
    mongodb:
      host: example.p.xxx.x
      port: 27017
      database: 데이터베이스 이름
      username: root
      password: 비밀번호
      authentication-database: admin
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
