server:
  port: 8081

spring:
    mvc:
      pathmatch:
        matching-strategy: ant_path_matcher
jpa:
  generate-ddl: false
  open-in-view: false
  hibernate:
    ddl-auto: validate # ???? ???? ?? ??????? ??
  properties:
    hibernate:
      format_sql: true
logging.level:
  org.hibernate.SQL: debug  # ?? hibernate? ???? SQL? ??? ??? ??? ? ??(?????? ??!)
  org.hibernate.type: trace