server:
  port: 8081

spring:
  datasource:
    url: 데이터베이스 url
    username: root
    password: 비밀번호
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: false
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

logging.level:
  org.hibernate.SQL: debug  # ?? hibernate? ???? SQL? ??? ??? ??? ? ??(?????? ??!)
  org.hibernate.type: trace

kakao.login:
  client_id: 아이디
  redirect_url: 콜백 주소

cloud:
  aws:
    s3:
      bucket: woonana
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      instanceProfile: true
