server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://k6b104.p.ssafy.io:3306/woonana
    username: root
    password: woonana123@
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false

jpa:
  generate-ddl: false
  open-in-view: false
  hibernate:
    ddl-auto: validate # ???? ???? ?? ??????? ??
  properties:
    hibernate:
      format_sql: true

logging.level:
  org.hibernate.SQL: debug  # ?? hibernate? ???? SQL? ??? ??? ??? ? ??(?????? ??!)
  org.hibernate.type: trace

kakao.login:
  client_id: 76d85e088d5bb875d6e4493b8eda78fd
  redirect_url: http://localhost:8080/oauth/callback
#
#server:
#  port: 8081
#
#spring:
#  mvc:
#    pathmatch:
#      matching-strategy: ant_path_matcher
#  devtools:
#    livereload:
#      enabled: true
#    restart:
#      enabled: false
#  freemarker:
#    cache: false
#    template-loader-path: classpath:/templates
#    suffix: .ftl
#
#jpa:
#  generate-ddl: false
#  open-in-view: false
#  hibernate:
#    ddl-auto: validate # ???? ???? ?? ??????? ??
#  properties:
#    hibernate:
#      format_sql: true
#
#logging.level:
#  org.hibernate.SQL: debug  # ?? hibernate? ???? SQL? ??? ??? ??? ? ??(?????? ??!)
#  org.hibernate.type: trace
#
#kakao.login:
#  client_id: 76d85e088d5bb875d6e4493b8eda78fd
#  redirect_url: http://localhost:8081/oauth/callback